// Generated by `npm run npc:audio`. Do not edit: change the lines in src/npc-voices/<god>.js and re-run.
export const AUDIO = {
  "ares": {
    "run_start": [
      {
        "path": "/npc-voices/ares/run_start_row-ferryman.wav",
        "text": "Row, ferryman.",
        "seconds": 1.84
      },
      {
        "path": "/npc-voices/ares/run_start_my-warriors-wait.wav",
        "text": "My warriors wait.",
        "seconds": 1.84
      }
    ],
    "rage_50": [
      {
        "path": "/npc-voices/ares/rage_50_i-saw-that.wav",
        "text": "I saw that.",
        "seconds": 1.2
      },
      {
        "path": "/npc-voices/ares/rage_50_careful-ferryman.wav",
        "text": "Careful, ferryman.",
        "seconds": 2.32
      }
    ],
    "rage_80": [
      {
        "path": "/npc-voices/ares/rage_80_last-warning.wav",
        "text": "Last warning!",
        "seconds": 1.6
      },
      {
        "path": "/npc-voices/ares/rage_80_deliver-them-now.wav",
        "text": "Deliver them now!",
        "seconds": 2
      }
    ],
    "hurry": [
      {
        "path": "/npc-voices/ares/hurry_hurry.wav",
        "text": "Hurry!",
        "seconds": 1.04
      },
      {
        "path": "/npc-voices/ares/hurry_hurry-ferryman.wav",
        "text": "HURRY, ferryman!",
        "seconds": 2.08
      },
      {
        "path": "/npc-voices/ares/hurry_row-faster-hurry.wav",
        "text": "Row faster! Hurry!",
        "seconds": 2.32
      },
      {
        "path": "/npc-voices/ares/hurry_souls-can-wait.wav",
        "text": "Souls can wait!",
        "seconds": 1.84
      }
    ],
    "shout": [
      {
        "path": "/npc-voices/ares/shout_row.wav",
        "text": "Row!",
        "seconds": 0.8
      },
      {
        "path": "/npc-voices/ares/shout_faster.wav",
        "text": "Faster!",
        "seconds": 1.04
      },
      {
        "path": "/npc-voices/ares/shout_ferryman.wav",
        "text": "Ferryman!",
        "seconds": 1.28
      },
      {
        "path": "/npc-voices/ares/shout_now.wav",
        "text": "Now!",
        "seconds": 1.04
      },
      {
        "path": "/npc-voices/ares/shout_fool.wav",
        "text": "Fool!",
        "seconds": 0.88
      },
      {
        "path": "/npc-voices/ares/shout_coward.wav",
        "text": "Coward!",
        "seconds": 1.12
      },
      {
        "path": "/npc-voices/ares/shout_mine.wav",
        "text": "Mine!",
        "seconds": 0.96
      },
      {
        "path": "/npc-voices/ares/shout_you-worm.wav",
        "text": "You worm!",
        "seconds": 1.36
      },
      {
        "path": "/npc-voices/ares/shout_row-now.wav",
        "text": "Row. Now!",
        "seconds": 1.6
      },
      {
        "path": "/npc-voices/ares/shout_move-ferryman.wav",
        "text": "Move, ferryman!",
        "seconds": 2.16
      }
    ],
    "streak": [
      {
        "path": "/npc-voices/ares/streak_better.wav",
        "text": "Better.",
        "seconds": 0.96
      },
      {
        "path": "/npc-voices/ares/streak_keep-rowing.wav",
        "text": "Keep rowing.",
        "seconds": 1.52
      }
    ],
    "smite": [
      {
        "path": "/npc-voices/ares/smite_enough-you-sink.wav",
        "text": "Enough! You sink.",
        "seconds": 2.32
      },
      {
        "path": "/npc-voices/ares/smite_the-river-takes-you.wav",
        "text": "The river takes you.",
        "seconds": 1.92
      }
    ]
  }
};
