// Records every god's lines with Gradium into public/npc-voices/<god>/<moment>_<text>.wav
// and writes src/npc-voices/manifest.js, the list getHeroAudio() picks from.
//   npm run npc:audio
// Gods without a kept voice (voiceId: null) are skipped. Files that already exist are kept,
// so re-running only records new or changed lines. One request at a time: Gradium allows 2.
// Needs GRADIUM_API_KEY in .env (never printed).
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { handleTTS } from '../server/tts.js';
import { NPCS, slugify } from '../src/npc-voices/heroes.js';

try {
  process.loadEnvFile?.('.env');
} catch {
  /* no .env file */
}

const OUT = 'public/npc-voices';
const MANIFEST = 'src/npc-voices/manifest.js';
const MAX_SECONDS = 2.5;
const RETRIES = 5;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Length of a WAV file in seconds, from its header. */
function wavSeconds(buf) {
  let offset = 12;
  let byteRate = 0;
  while (offset + 8 <= buf.length) {
    const id = buf.toString('ascii', offset, offset + 4);
    const size = buf.readUInt32LE(offset + 4);
    if (id === 'fmt ') byteRate = buf.readUInt32LE(offset + 16);
    if (id === 'data') return byteRate ? Math.min(size, buf.length - offset - 8) / byteRate : 0;
    offset += 8 + size + (size & 1);
  }
  return 0;
}

async function record(text, voice, file) {
  for (let attempt = 1; attempt <= RETRIES; attempt++) {
    const res = await handleTTS({ text, voice });
    if (res.audio) return writeFileSync(file, res.audio);
    const error = res.json?.error || `HTTP ${res.status}`;
    if (res.json?.mock) throw new Error('No GRADIUM_API_KEY in .env');
    if (attempt === RETRIES || !/concurrency|timed out|429/i.test(error)) throw new Error(error);
    await sleep(1000 * attempt);
  }
}

if (!process.env.GRADIUM_API_KEY) {
  console.log('No GRADIUM_API_KEY in .env: nothing recorded.');
  process.exit(1);
}

const audio = {};
let made = 0;
let failed = 0;
const long = [];

for (const [hero, npc] of Object.entries(NPCS)) {
  if (!npc.voiceId) {
    console.log(`${npc.name}: no voice kept yet, skipped`);
    continue;
  }
  const dir = `${OUT}/${hero}`;
  mkdirSync(dir, { recursive: true });
  const expected = new Set();
  audio[hero] = {};

  for (const [moment, lines] of Object.entries(npc.lines)) {
    audio[hero][moment] = [];
    for (const text of lines) {
      const name = `${moment}_${slugify(text)}.wav`;
      const file = `${dir}/${name}`;
      expected.add(name);
      if (!existsSync(file)) {
        try {
          await record(text, npc.voiceId, file);
          made++;
          console.log(`  + ${hero}/${name}  "${text}"`);
        } catch (err) {
          failed++;
          console.log(`  ! ${hero}/${name}  ${err.message}`);
          continue;
        }
      }
      const seconds = Math.round(wavSeconds(readFileSync(file)) * 100) / 100;
      if (seconds > MAX_SECONDS) long.push(`${hero}/${name} (${seconds}s)  "${text}"`);
      audio[hero][moment].push({ path: `/npc-voices/${hero}/${name}`, text, seconds });
    }
  }

  const stale = readdirSync(dir).filter((f) => f.endsWith('.wav') && !expected.has(f));
  if (stale.length) console.log(`${npc.name}: files no longer in the lines, safe to delete:\n    ${stale.join('\n    ')}`);
  console.log(`${npc.name}: ${Object.values(audio[hero]).flat().length} lines`);
}

writeFileSync(
  MANIFEST,
  `// Generated by \`npm run npc:audio\`. Do not edit: change the lines in src/npc-voices/<god>.js and re-run.\n` +
    `export const AUDIO = ${JSON.stringify(audio, null, 2)};\n`,
);

console.log(`\nRecorded ${made} new file(s), ${failed} failed. Manifest: ${MANIFEST}`);
if (long.length) console.log(`Longer than ${MAX_SECONDS}s, consider shortening:\n  ${long.join('\n  ')}`);
if (failed) process.exit(1);
