// Records every god's lines with Gradium and ships them as public/npc-voices/<god>/<moment>_<text>.mp3,
// then writes src/npc-voices/manifest.js, the list getHeroAudio() picks from.
//   npm run npc:audio
// Per line: the MP3 exists -> kept. Else the WAV original in voice-candidates/masters/ (gitignored)
// is converted. Else the line is recorded with Gradium (WAV), then converted. So re-running only
// pays for new or changed lines. Gods without a kept voice (voiceId: null) are skipped.
// Needs GRADIUM_API_KEY in .env (never printed) to record, and ffmpeg to convert (not to play the game).
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { handleTTS } from '../server/tts.js';
import { NPCS, slugify } from '../src/npc-voices/heroes.js';

try {
  process.loadEnvFile?.('.env');
} catch {
  /* no .env file */
}

const OUT = 'public/npc-voices';
const MASTERS = 'voice-candidates/masters';
const MP3 = ['-codec:a', 'libmp3lame', '-ac', '1', '-b:a', '64k']; // mono 64 kbps: plenty for one voice
const MANIFEST = 'src/npc-voices/manifest.js';
const MAX_SECONDS = 2.5;
const LONG_MOMENTS = new Set(['verdict']); // long on purpose (game over): no length warning
const MAX_NAME = 60; // file names stay readable even for long lines
const RETRIES = 5;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function hasTool(name) {
  try {
    execFileSync(name, ['-version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

const toMp3 = (wav, mp3) => execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', wav, ...MP3, mp3]);

/** File name part of a line, cut at a word boundary so long lines keep readable names. */
function shortSlug(text) {
  const slug = slugify(text);
  if (slug.length <= MAX_NAME) return slug;
  const cut = slug.slice(0, MAX_NAME + 1);
  return cut.slice(0, cut.lastIndexOf('-'));
}

/** Length of an audio file in seconds. */
const seconds = (file) =>
  Number(execFileSync('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file]).toString());

async function record(text, voice, file) {
  for (let attempt = 1; attempt <= RETRIES; attempt++) {
    const res = await handleTTS({ text, voice });
    if (res.audio) return writeFileSync(file, res.audio);
    const error = res.json?.error || `HTTP ${res.status}`;
    if (res.json?.mock) throw new Error('No GRADIUM_API_KEY in .env');
    if (attempt === RETRIES || !/concurrency|timed out|429/i.test(error)) throw new Error(error);
    await sleep(1000 * attempt);
  }
}

if (!hasTool('ffmpeg') || !hasTool('ffprobe')) {
  console.log('ffmpeg is needed to make the MP3s: sudo apt install ffmpeg (Linux/WSL) or brew install ffmpeg (Mac).');
  process.exit(1);
}

const audio = {};
let made = 0;
let converted = 0;
let failed = 0;
const long = [];

for (const [hero, npc] of Object.entries(NPCS)) {
  if (!npc.voiceId) {
    console.log(`${npc.name}: no voice kept yet, skipped`);
    continue;
  }
  const dir = `${OUT}/${hero}`;
  const masters = `${MASTERS}/${hero}`;
  mkdirSync(dir, { recursive: true });
  mkdirSync(masters, { recursive: true });
  const expected = new Set();
  audio[hero] = {};

  for (const [moment, lines] of Object.entries(npc.lines)) {
    audio[hero][moment] = [];
    for (const text of lines) {
      const base = `${moment}_${shortSlug(text)}`;
      const name = `${base}.mp3`;
      const file = `${dir}/${name}`;
      const wav = `${masters}/${base}.wav`;
      expected.add(name);
      if (!existsSync(file)) {
        try {
          if (!existsSync(wav)) {
            if (!process.env.GRADIUM_API_KEY) throw new Error('not recorded yet and no GRADIUM_API_KEY in .env');
            await record(text, npc.voiceId, wav);
            made++;
          }
          toMp3(wav, file);
          converted++;
          console.log(`  + ${hero}/${name}  "${text}"`);
        } catch (err) {
          failed++;
          console.log(`  ! ${hero}/${name}  ${err.message}`);
          continue;
        }
      }
      const length = Math.round(seconds(file) * 100) / 100;
      if (length > MAX_SECONDS && !LONG_MOMENTS.has(moment)) long.push(`${hero}/${name} (${length}s)  "${text}"`);
      audio[hero][moment].push({ path: `/npc-voices/${hero}/${name}`, text, seconds: length });
    }
  }

  const stale = readdirSync(dir).filter((f) => !expected.has(f));
  if (stale.length) console.log(`${npc.name}: files no longer in the lines, safe to delete:\n    ${stale.join('\n    ')}`);
  console.log(`${npc.name}: ${Object.values(audio[hero]).flat().length} lines`);
}

writeFileSync(
  MANIFEST,
  `// Generated by \`npm run npc:audio\`. Do not edit: change the lines in src/npc-voices/<god>.js and re-run.\n` +
    `export const AUDIO = ${JSON.stringify(audio, null, 2)};\n`,
);

console.log(`\nRecorded ${made} line(s) with Gradium, made ${converted} MP3(s), ${failed} failed. Manifest: ${MANIFEST}`);
if (long.length) console.log(`Longer than ${MAX_SECONDS}s, consider shortening:\n  ${long.join('\n  ')}`);
if (failed) process.exit(1);
